Permute Seminar, Week 1
========================================================

Load the libraries that we will need for examples
```{r}
library(ggplot2)
library(boot)
library(bootstrap)

se <- function(x) sqrt(var(x)/length(x))
```

**For Week 3:**

**Notes:**
-------------

**From the text:**
--------------------
Chapter 3
----------

* a random sample is a collection of n units from "universe" of individuals, U

**Law school dataset:**
A random sample of 15 was taken from a population of 82 schools. The data is average LSAT score and GPA.

```{r}
lsat = c(576, 635, 558, 578, 666, 580, 555, 661, 651, 605, 653, 575, 545, 572, 594)
gpa = c(3.39, 3.30, 2.81, 3.03, 3.44, 3.07, 3.00, 3.43, 3.36, 3.13, 3.12, 2.74, 2.76, 2.88, 2.96)
school = data.frame(lsat,gpa)

ggplot(school, aes(lsat, gpa)) + geom_point() + theme_classic() + stat_smooth(method = "lm") + 
  theme(text = element_text(size=20)) + xlab("average LSAT score") + ylab ("average GPA")

print (mean(lsat))
print (se(lsat))

print (paste("There is a", 68 ,"% chance that the true LSAT mean lies in the interval", round(mean(lsat),2), 
             "+/-", round(se(lsat),2)))
```

**probability theory review**
* Statistical inference is about using a random sample to infer properties of the complete population
* Probability is about understanind the propties of a sample from the population, and of statistics calculated from the sample.

Probability distributions:

Binomial distribution has size n with probability success p.
```{r}
d = rbinom(1000, 1, 1/2)
hist(d, main = "binomial distribution", col = "indianred")
```

Normal distribution has mean u and variance sigma
```{r}
d = rnorm(1000, 1:5)
hist(d, main = "normal distribution", col = "cadetblue")
```

The expectation of a random variable E(x) is its average value where the average is taken over the possible outcomes of x weighted by its probabilty distribution F.

Random sampling with replacement guarantees independence of two variables, because all n observations of x will be identically distributed and mutually independent of each other.



Chapter 4
----------
**the empirical distribution function**

