Null models - native and introduced species
========================================================

Simulating native-exotic relationships at different spatial scales
--------------------------------------------------------------------
Modified from the Fridley et al. code

```{r}

## Parameters  												  

reps<-100			#number of replicates for each sample size

samps<-c(5,10,20,50,100,800)	#sample sizes, in number of represented individuals

pool.range<-c(20,100)		#range of species richness of total species pool (includes natives, exotics, and "bare spaces")

NEprop<-c(.75,.15,.1)		#proportion of, respectively, natives, exotics, and bare spaces in pool (totals to 1)


#Output holding array:
#row 1 is native richness
#row 2 is exotic richness
#columns are sample sizes
#3rd dimension is replicates, of length [reps]

output<-array(0,dim=c(2,length(samps),reps))

tot.pool<-round(runif(reps,pool.range[1],pool.range[2]))	#randomly generate [reps]-length vector of total pool sizes

## LOOP over replicates

for (j in 1:reps){

	print(j)	#progress output

	#determine pool composition for replicate

	natives<-paste("N",c(1:round(NEprop[1]*tot.pool[j])))	#list of native species
	exotics<-paste("E",c(1:round(NEprop[2]*tot.pool[j])))	#list of exotic species
	zeros<-paste("Z",c(1:round(NEprop[3]*tot.pool[j])))	#list of free spaces
  
  #list of all species and blanks
	allspp<-c(natives,exotics,zeros)				

	#randomly construct simulated community

	ind.vec<-floor(rlnorm(length(allspp),8,1))		#create list of abundances for each species, from lognormal abundance distribution

	comm<-rep(allspp[1],ind.vec[1])				#populate first species in pool with its associated abundance

	for(i in 2:length(allspp)) {				#loop over all remaining species

		comm<-c(comm,rep(allspp[i],ind.vec[i]))		#populate remaining species with associated abundances

	}

	#sample community using different sample sizes

	
  
  for(i in 1:length(samps)) {					#LOOP for different sample sizes

		rs<-sample(comm,samps[i])					#draw randomly from community pool of individuals with given sample size

		output[1,i,j]<-length(unique(rs[is.element(rs,natives)]))	#total richness of natives in the sample

		output[2,i,j]<-length(unique(rs[is.element(rs,exotics)]))	#total richness of exotics in the sample

	}	#end sample size loop		

}		#end replicate loop

```

Making figures
```{r}

## Plot native-exotic richness relationship of largest sampling size (800 indivs)
 
plot(output[1,6,],output[2,6,],pch=".",xlab="native richness",ylab="exotic richness",xlim=c(0,max(output[1:2,6,])),ylim=c(0,max(output[1:2,6,])))

abline(lsfit(output[1,6,],output[2,6,]))		#least-squares regression line


## Plot native-exotic richness relationship of next smallest sampling size (100 indivs)

plot(output[1,5,],output[2,5,],pch=".",xlab="native richness",ylab="exotic richness",xlim=c(0,samps[5]),ylim=c(0,samps[5]))

abline(lsfit(output[1,5,],output[2,5,]))		#least-squares regression line

abline(samps[5],-1,lty=4)				#data constraint envelope, based on sample size

## Plot native-exotic richness relationship of next smallest sampling size (50 indivs)

plot(output[1,4,],output[2,4,],pch=".",xlab="native richness",ylab="exotic richness",xlim=c(0,samps[4]),ylim=c(0,samps[4]))

abline(lsfit(output[1,4,],output[2,4,]))		#least-squares regression line

abline(samps[4],-1,lty=4)				#data constraint envelope, based on sample size

## Plot native-exotic richness relationship of next smallest sampling size (20 indivs)

plot(jitter(output[1,3,]),jitter(output[2,3,]),pch=".",xlab="native richness",ylab="exotic richness",xlim=c(0,samps[3]),ylim=c(0,samps[3]))

abline(lsfit(output[1,3,],output[2,3,]))  	#least-squares regression line

abline(samps[3],-1,lty=4)				#data constraint envelope, based on sample size

## Plot native-exotic richness relationship of next smallest sampling size (10 indivs)


plot(jitter(output[1,2,]),jitter(output[2,2,]),pch=".",xlab="native richness",ylab="exotic richness",xlim=c(0,samps[2]),ylim=c(0,samps[2]))

abline(lsfit(output[1,2,],output[2,2,]))  	#least-squares regression line

abline(samps[2],-1,lty=4)				#data constraint envelope, based on sample size


## Plot native-exotic richness relationship of next smallest sampling size (5 indivs)

plot(jitter(output[1,1,]),jitter(output[2,1,]),pch=".",xlab="native richness",ylab="exotic richness",xlim=c(0,samps[1]),ylim=c(0,samps[1]))

abline(lsfit(output[1,1,],output[2,1,]))		#least-squares regression line

abline(samps[1],-1,lty=4)				#data constraint envelope, based on sample size
```

Testing observed data against the null model
---------------------------------------------
Importing the observed data

```{r}
require(RCurl)
options(RCurlOptions = list(cainfo = system.file("CurlSSL", "cacert.pem", package = "RCurl")))
      
raw <- getURL("https://raw.githubusercontent.com/PermuteSeminar/PermuteSeminar-2014/master/Week-10/speciescounts.csv")
spcounts <- read.csv(text = raw) 


```



Creating a site by species matrix at the quadrat scale
```{r}
require(reshape)
quadmat<- cast(spcounts,  Site + Quadrat ~ Species, value='Count', fun=sum) #sums the number of individual plants per quadrat

quadmat <- as.data.frame(quadmat) #fixes the recast as a data frame
quadmat[is.na(quadmat)] <- 0 #refills the empty cells with 0
```


Creating a site by species matrix at the site scale
```{r}
require(reshape)
columnquad<-melt(quadmat, id=c('Site', 'Quadrat'))

sitemat <- cast(columnquad, Site ~ Species, value='value', fun=sum) #sums the number of individual plants per quadrat

sitemat <- as.data.frame(sitemat) #fixes the recast as a data frame
quadmat[is.na(quadmat)] <- 0 #refills the empty cells with 0
```


