Emily Rollinson Week 13
========================================================

Data from Svoboda et al. 2014 - Spatial and temporal community structure of desmids

Load packages
```{r}
require(RCurl)
require(vegan)
require(ggplot2)
```

Load data
```{r}
comm<-read.csv("Svoboda_transpose.csv", row.names=1)
groups<-read.csv("EJR_siteinfo.csv")
```

Run NMDS - plots the three different sites

```{r}
ord<-metaMDS(comm, distance="bray", k=3, trymax=50)
plot(ord, display="sites")

#or in ggplot
points<-as.data.frame(ord$points)
points <- cbind(points, type = groups$Type)
ggplot(points,aes(x=MDS1, y=MDS2, col=type)) + geom_point()
#this is color-coded for bogs vs. fens, you could color code the pools as well
```

Run anosim on the various groupings

```{r}
#Difference between fen and bog
anosim(comm, groups$Type, permutations=999, distance="bray")

#Differences among fens
anosim(comm[1:9,], groups[1:9,]$Site, permutations=999, distance="bray")

#Differences among bogs
anosim(comm[10:18,], groups[10:18,]$Site, permutations=999, distance="bray")
```

Significant differences at all levels: between fen and bog (aka Swamp vs. NaCihadle); among pools in fens; among pools in bogs.